# Generated by Django 4.1.7 on 2023-05-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
