# Generated by Django 4.1.7 on 2023-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
